name: Manually Triggered Workflow
on:
  workflow_dispatch:

jobs:
  test-run1:
    name: cd / Build Init
    runs-on: ubuntu-latest
    steps:
      - run: echo "Just try a run"
  test-run2:
    name: cd / [STG] Terraform Apply (ap-southeast-1/fpr-affiliate/fprdsaf/api-gateway/vpc-link/)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Just try a run"
  test-run3:
    name: cd / [PROD] Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - run: echo "Just try a run"
  test-run4:
    name: cd / [STG] Terraform Apply (staging/ap-southeast-1/fpr-affiliate/fpraff/api-gateway/rest_api/)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Just try a run"
  test-run5:
    name: cd / [PROD] Terraform Apply (ap-southeast-1/fpr-affiliate/fprdsaf/api-gateway/vpc-link/)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Just try a run"

  test-workflow:
    name: Test Workflow
    runs-on: ubuntu-latest
    needs: [test-run1, test-run2, test-run3, test-run4, test-run5]

    # actions.read permission is required.
    # other three are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      actions: 'read'
      pull-requests: write
      id-token: write
      contents: read

    steps:
      - name: Slack Workflow Notification
        uses: ichsansting/slack-workflow-status@master
        id: slack_workflow_notification
        with:
          # Required Input
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.LARK_WEBHOOK_URL }}
          # Optional Input
          name: 'Terraform FPR Prod'
      - run: echo ${{ steps.slack_workflow_notification.outputs.data }}
      - run: echo ${{ steps.slack_workflow_notification.outputs.response }}
